# tasks/main.yml
---
- name: Ensure systemd unit prerequisites {{ systemd_unit_name }}
  ansible.builtin.import_tasks: prerequisites.yml

- name: Ensure systemd unit {{ systemd_unit_name }}
  ansible.builtin.import_tasks: systemd_unit.yml
